-- MIN CITY NAME AND MAX CITY MANE WITH LENGTH --

SELECT CITY, CHAR_LENGTH(CITY) FROM STATION 
WHERE CHAR_LENGTH(CITY) IN (
  SELECT MAX(CHAR_LENGTH(CITY)) FROM STATION
UNION 
  SELECT MIN(CHAR_LENGTH(CITY)) FROM STATION
) ORDER BY CHAR_LENGTH(CITY) DESC, CITY LIMIT 2;
